bump_version: null
lint: null
nf_core_version: 3.0.1
org_path: null
repository_type: pipeline
template:
  author: Daniel Lundin
  description: Performs phylogenetic placement with EPA-NG
  force: false
  is_nfcore: true
  name: phyloplace
  org: nf-core
  outdir: .
  skip_features: null
  version: 1.1.0dev
update: null
